### PR TITLE
onl: update to HEAD from 2022-04-07

### PR DESCRIPTION
**Pull request by KanjiMonster**
- Update onl to latest HEAD, adding these commits:

 * eba33a57 Change variable length to fix buffer-over-flow issue
 * 928bf5cb Enable kernel modules for jc42 and eMMC in v4.19 kernel config
 * 8ec2b826 [S9705-48D] Add platform S9705-48D
 * 4da10fec [S9700-23D] Add platform S9700-23D
 * 1fdd6e50 [S9700-53DX] Add platform S9700-53DX
 * bd7584a6 [as4610-54t] Take off the redundant code
 * b9aa4e17 [as4610-54t] Support PSU YM-1151F PSU YM-1151F can be supported by the existing code, so just make the new model name known.
 * d6bad675 [as7946_74xkb] Add new platform CPU: Intel Broadwell-DE Xeon 1548, 8-core MAC: Broadcom BCM88823 TAP: Broadcom BCM5235 BMC: AST2600 CPLD: Intel 5M2210ZF324C5N (3pcs, FBGA324 package) Ethernet Port: 2 x 100G QSFP-DD (only support high power 100G optics)                8 x 100G QSFP28                64 x 25G SFP28 Power Supply: AC/DC or DC/DC max 1300W output, 1 + 1 redundant load-sharing Cooling: 5pcs hot swappable 6076, 12V fan, support 4 + 1 mode Dimension: 440mm (Width) x 480mm (Depth) x 87 mm (Height)
 * 1637098a Revert "[Delta][AGCV208S] Add AGCV208S platform"
 * 46abc773 Revert "Update existed platform Inventec D6432 and new platform D6356J and D7032Q28B (support ONLP)"
 * 5b0f6e97 [as4610-54t] Support PSU YM-1151F PSU YM-1151F can be supported by the existing code, so just make the new model name known.
 * 401ce9b9 [as5915-18x] Fix error message in psui.c 1.  Only AC PSU needs to show serial number.
 * 2158173c Add OnlPlatformPortConfig_48x1_4x25.
 * de249e9d Add new platform SCG60D0-484T
 * b7c27ef9 [asgvolt64] PSU identifying AC or DC 1. Add vout_mode for DC PSU 2. To judge PSU model for identifying AC or DC
 * b6b71a0a [asgvolt64] PSU pmbus data for identifying the fail or unplugged case 1. Add VIN to psui.c 2. Add condition to judge the fail or unplugged case
 * 015160fc Add new platform SNJ61D0-320F
 * 701372ce [as7535_28xb] Add new platform
 * 083d4fdf [as4630_54te] Add new platform
 * 90b19b4e [as7315_30x] Add thermal policy and thermal threshold
 * 766f1ee8 Fix high threshold condition judgement
 * 20222d10 Change invalid fanlevel jump to adjacent level
 * ed24bc49 Update AS7816-64X thermal plan
 * 24efd4f4 [as4610] Support Delta PSU DPS-920AB
 * 48349959 [as7315_30x] Add new platform
 * b7ce69b2 [es7632bt3] Add new platform
 * db0f9ce1 [accton/asxvolt16] Add a sysfs to get and set the qsfp lp mode
 * 9a907769 [accton/asxvolt16] Apply the Linux coding style to x86-64-accton-asxvolt16-sfp.c
 * b106021d [as9926_24db] Add new platform
 * be9480a3 [as9926-24d] Support FSJ033-610G DC PSU
 * 12893c5d [accton/as5915-18x] Support AC PSU on ONL
 * 37ea5f92 [accton/as7315-27xb] Remove redundant condition in psui.c
 * a4117ae5 Restruct platform D6432 and ONLP
 * 1e4c1969 Support platform D6356J and ONLP
 * 76e13f0b Support ONLP for D7032Q28B
 * 3d3dd471 Updage inv_platform driver for D6432  - Remove soft link with D7332 for they're not using same drivers now  - Update ONLP and init script according to driver changes
 * 95c4c24c [accton/as7315-27xb] Support AC PSU on ONL
 * f5f9c5ba Add new platform SNJ60D0-320F
 * 34f609dc [accton/wedge100bf-65x] Fix some onlpi errors at onlpd.log
 * 07674f0c Beta build HW modify, front panel PSU-1/PSU-2 exchanged and rear panel FAN 1-4 sort exchanged.
 * 8b8df1fd [Delta][AGCV208S] Add AGCV208S platform
 * 678a6a38 [as7326-56x] Support ACBEL FSF019 PSU
 * 265d87f0 [as7726-32x] Support ACBEL FSF019 PSU
 * 6dcafc9d [as7716-32x] Support ACBEL FSF019 PSU
 * aee227a1 [AS5916-54XL] display rear fans info
 * 1e5490e7 [ag9032v2] Add kernel modules probe to platform init script.
 * ed6aa671 [as5835-54t] support new DC PSU
 * 48ef3aed [as7926_40xfb] Add new platform
 * d92cf60f [as7326-56x] support eeprom at addr 0x56 and 0x57
 * 669f3f79 [Accton] Fix memory leak if PSU1 is not present
 * 0de1c305 [Accton] Fix memory leak if PSU1 is not present
 * 554ece9e [Netberg][nba820] Initital support for Netberg Aurora 820 400G switch
 * 6aa0312d [as9516-32d] Add as9516-32d platform 1. Broadwell-DE, Pentium D-1517,4C,1.4GHz,6MB,25W 2. JBAY-12.8 provides 256 x 56G SERDES links for a total of 12.8 Tbps throughput 3. 32 QSFP-DD 400Gbps network ports 4. Integrate barefoot fpga code into ONL 5. The barefoot code need to maintain or fixed by barefoot 6. Need to turn on config "CONFIG_USB_ACM" since we use "/dev/ttyACM0" to access bmc
 * ab898097 [as4630-54pe] Fix fan LED always showing fan is turned off
 * fd11660a [as9716-32d] Modify fan/psu sys-led due to HW control led
 * 120169b2 [accton/wedge100bf-32x] Fix error on polling fan and psu
 * 1f0aa964 [accton/wedge100bf-32x] Correct the PSUs' info
 * dc8baf04 [accton/wedge100bf-32x] Call bmc_tty_init() at init
 * d8124731 [Ingrasys] update PORT_COUNT and PORT_CONFIG for init at all platform
 * 544cbfdc [s9280] init all chnl as input in 0x25 io expander on dummy card to avoid power button trigger
 * 40a3e81c [as4630-54pe] Add newline at end of file
 * f6b6e69b [as4630-54pe] Rename eth2 as ma1 to make management port work
 * 318515d4 [as4630_54pe] Fix platform port config
 * b6816758 [asxvolt16] Update thermal threshold of PSU module
 * 8f456873 [asgvolt64/asxvolt16] Update thermal threshold
 * cc801ea8 Validate tx_disable function of 4 SFP+ ports.
 * fcde50bb [s9180] fix wrong color for fan fail on fan tray led
 * 43cedcf1 [s9180] remove unused variable in platform_lib.c
 * c56c0651 [s9180] fix fan panel index mismatch with hwm sysfs and led index

- Drop patches applied upstream:
 * 0001-Validate-tx_disable-function-of-4-SFP-ports.patch
 * 0001-as4630-54pe-Fix-fan-LED-always-showing-fan-is-turned.patch
 * 0010-Support-ACBEL-FSF019-PSU.patch

- Drop unneeded patch 0008-add_48x25_8x100_PlatformPortConfig.patch, it
  does not apply anymore and there already is a
  48x25_8x100_PlatformPortConfig, no need to add a second one.

- Refresh/rebase patches:
 * 0001-onl-as5835-don-t-ignore-PSU2_AC_PMBUS_NODE.patch
 * 0002-as5835-rename-psu_serial_numer-psu_serial_number.patch

- Update accton-as4610_psu.c and ym2651y.c according to state in HEAD.
- Update optoe to state in HEAD, adding QSFP-DD (400G) support.

Signed-off-by: Jonas Gorski <jonas.gorski@bisdn.de>

### CODE REVIEW

**Comment by ideaship** [comment]
The second commit in this PR seems to have been included by accident. If it was part of the ONL update, I would expect it to be part of the first commit. If it wasn't part of the ONL update, it wouldn't be in the PR.

If it is really meant to be part of the PR, then I find the commit message confusing:

- f5dd66b4aa36 is not ("update optoe drvier ( QSFP-DD support)"
  - f5dd66b4 [oom] Correct a panic inducing defect which is triggered on a read (or write)
  - b1c836c8 update optoe drvier ( QSFP-DD support)
- This comment is rather cryptic if you don't already know what it means:
  - [jonas.gorski: i2c_new_dummy => i2c_new_dummy_device for kernel 5.15 compatibility]
- shouldn't the original author be mentioned somewhere?

**Review by ideaship — CHANGES_REQUESTED** [review]
See comment on second commit.

**Comment by KanjiMonster** [comment]
> The second commit in this PR seems to have been included by accident. If it was part of the ONL update, I would expect it to be part of the first commit. If it wasn't part of the ONL update, it wouldn't be in the PR.

It was more like I noticed we never updated our optoe driver, and since this change was from before the "old" version, it isn't part of the changes between the old and the new onl, I decided it should be a separate commit (but still part of the "get onl to the newest version" changeset).

> If it is really meant to be part of the PR, then I find the commit message confusing:
> 
>     * f5dd66b4aa36 is not ("update optoe drvier ( QSFP-DD support)"
>       
>       * f5dd66b4 [oom] Correct a panic inducing defect which is triggered on a read (or write)
>       * b1c836c8 update optoe drvier ( QSFP-DD support)

Ups, copied the wrong commit hash. Fixed.

>     * This comment is rather cryptic if you don't already know what it means:
>       
>       * [jonas.gorski: i2c_new_dummy => i2c_new_dummy_device for kernel 5.15 compatibility]

Kernel API changed, and i2c_new_dummy was eventually dropped, with i2c_new_dummy_device being the replacement.

> 
>     * shouldn't the original author be mentioned somewhere?

Updated the commit to have the original author and commit date (to make it more clear that this is something we missed previously).

**Comment by ideaship** [comment]
Much better now. Thanks!

**Pull request merged**
