### PR TITLE
fix remaining ONIE_MACHINE_TYPEs

### PR DESCRIPTION
**Pull request by KanjiMonster**
ONIE uses underscores, not dashes, so ONIE_MACHINE_TYPE should not contain any dashes.

Signed-off-by: Jonas Gorski <jonas.gorski@bisdn.de>

### CODE REVIEW

**Comment by ideaship** [comment]
While you're at it, could you add a commit to fix the as7726-32x which appears to have the same problem?

Also, the commit message should explain why this wasn't caught earlier. Does it not matter at all?

**Comment by KanjiMonster** [comment]
I noticed the fix is broken anyway.

**Comment by KanjiMonster** [comment]
It's needed for the installer, which relies on correct ONIE platform names.

**Comment by KanjiMonster** [comment]
> Also, the commit message should explain why this wasn't caught earlier.

Not sure why this matters. So far nothing uses it, so it being broken didn't matter. And caught this time because I was looking it as I was looking at the wiki stuff.

**Pull request merged**
