### PR TITLE
linux-yocto-onl: enable some crypto code on armel-iproc

### PR DESCRIPTION
**Pull request by ideaship**
Align armel-iproc with intel-x86 to resolve this build warning:

  do_kernel_configcheck: [kernel config]: specified values did not make it
  into the kernel's final configuration:
  [...]

All affected options are changed to match whatever the intel-x86 config does.

### CODE REVIEW

**Comment by KanjiMonster** [comment]
Please don't leave out the actual error/warning message.

**Comment by ideaship** [comment]
The actual message comes in several parts. If you fix some options, messages regarding additional symbols pop up. I don't think it's necessary to list them all here.

**Comment by KanjiMonster** [comment]
Without knowing what the output is it's hard telling if this is the correct fix.

**Comment by KanjiMonster** [comment]
> Here you go:
> 
> ```
> Oct 24 07:31:20 WARNING: linux-yocto-onl-5.15.64+gitAUTOINC+8fa8d5e477_1ded0ef241-r0 do_kernel_configcheck: [kernel config]: specified values did not make it into the kernel's final configuration:
> Oct 24 07:31:20 
> Oct 24 07:31:20     [NOTE]: 'CONFIG_CRYPTO_AUTHENC' last val (n) and .config val (m) do not match
> Oct 24 07:31:20     [INFO]: CONFIG_CRYPTO_AUTHENC : m ## .config: 3818 :configs//bsp/armel-iproc/armel-iproc.cfg (n) 
> Oct 24 07:31:20     [INFO]: raw config text:
> Oct 24 07:31:20 
> Oct 24 07:31:20         config CRYPTO_AUTHENC
> Oct 24 07:31:20         	tristate "Authenc support"
> Oct 24 07:31:20         	select CRYPTO_AEAD
> Oct 24 07:31:20         	select CRYPTO_SKCIPHER
> Oct 24 07:31:20         	select CRYPTO_MANAGER
> Oct 24 07:31:20         	select CRYPTO_HASH
> Oct 24 07:31:20         	select CRYPTO_NULL
> Oct 24 07:31:20         	depends on CRYPTO
> Oct 24 07:31:20         	help
> Oct 24 07:31:20         	  Authenc: Combined mode wrapper for IPsec.
> Oct 24 07:31:20         	  This is required for IPSec.
> Oct 24 07:31:20 
> Oct 24 07:31:20         Config 'CRYPTO_AUTHENC' has the following Direct dependencies (CRYPTO_AUTHENC=y):
> Oct 24 07:31:20                 CRYPTO(=y)
> Oct 24 07:31:20         Parent dependencies are:
> Oct 24 07:31:20              CRYPTO [y]
> Oct 24 07:31:20 
> Oct 24 07:31:20     [INFO]: selection details for 'CONFIG_CRYPTO_AUTHENC':
> Oct 24 07:31:20         Symbols currently m-selecting this symbol:
> Oct 24 07:31:20           - XFRM_ESP
> ```

I guess these warnings were introduced in https://github.com/bisdn/meta-open-network-linux/commit/039d54a1ef812b7bf2d50ecde61a7dfcfddd2cb1, where we enable INET_ESP.

Can you please add an appropriate Fixes-tag and the output to the commit message?

**Comment by ideaship** [comment]
I doubt the wisdom of having a 500+ line commit message which is largely redundant, but it's done.

**Review by KanjiMonster — APPROVED** [review]
Having the error message makes it easier to find when encountering the same/similar one for others, and makes it easier to review. In general it's good to always include the actual error/warning message(s) verbatim, be it bug reports or commit messages.

I'm unsure about the switch to built-in, as I don't see why it should be needed. OTOH, I faintly remember crypto being a bit finicky with on-demand loading (or was it compression?), so I'll allow it. I'll be nice and don't force you to split this ;P.

We might want to consider moving these symbols to a snippet in the future, as these are non-hardware related

**Pull request merged**
